examples/src/main/python/exampleHIVE.py, examples/src/main/scala/SimpleHiveContext.scala, mist.sbt, project/plugins.sbt, src/main/resources/reference.conf, src/main/scala/com/provectus/mist/Constants.scala, src/main/scala/com/provectus/mist/actors/ContextManager.scala, src/main/scala/com/provectus/mist/jobs/Job.scala, src/test/python/HIVE.py, src/test/python/SQL.py, src/test/python/SparkContext.py, src/test/python/TestError.py, src/test/resources/SimpleSQLContextData.json, src/test/resources/reference.conf, src/test/scala/HiveContext.scala, src/test/scala/SQLContext.scala, src/test/scala/SparkContext.scala, src/test/scala/TestConfig.scala, src/test/scala/TestError.scala, src/test/scala/TestMqttSubPub.scala, src/test/scala/Testmist.scala, src/test/scala/noDoStuffMethodError.scala
=>  Added tests for all

README.md
Cosmetic Documentation updates
=> Cosmetic Documentation updates

README.md
=> Minor styling fixes

README.md
=> Walker proofread Mist README

src/main/scala/io/hydrosphere/mist/jobs/jar/JobInstance.scala, src/test/scala/io/hydrosphere/mist/jobs/jar/JobInstanceSpec.scala, src/test/scala/io/hydrosphere/mist/jobs/jar/testJobs.scala
=> Save order of arguments for scala jobs. See #198

src/main/scala/io/hydrosphere/mist/master/FrontendJobExecutor.scala, src/test/scala/io/hydrosphere/mist/master/FrontendExecutorSpec.scala, src/test/scala/io/hydrosphere/mist/worker/WorkerActorSpec.scala
=> Job should be submitted only once

configs/router-examples-spark1.conf, src/main/scala/io/hydrosphere/mist/worker/runners/scala/ScalaRunner.scala, src/main/scala/org/apache/spark/util/SparkClassLoader.scala
=> Use spark classloaders

docs/http_api.md, src/main/scala/io/hydrosphere/mist/Messages.scala, src/main/scala/io/hydrosphere/mist/jobs/JobDetails.scala, src/main/scala/io/hydrosphere/mist/master/FrontendJobExecutor.scala, src/main/scala/io/hydrosphere/mist/master/MasterService.scala, src/main/scala/io/hydrosphere/mist/master/StatusService.scala, src/main/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2.scala, src/main/scala/io/hydrosphere/mist/master/store/H2JobsRepository.scala, src/main/scala/io/hydrosphere/mist/master/store/JobRepository.scala, src/test/scala/io/hydrosphere/mist/master/StatusServiceSpec.scala, src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2Spec.scala, src/test/scala/io/hydrosphere/mist/master/store/H2RepoSpec.scala
For example: `/v2/api/jobs?status=started&status=canceled`
=> http - status filter for jobs

src/main/scala/io/hydrosphere/mist/master/MasterService.scala, src/main/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2.scala, src/test/scala/io/hydrosphere/mist/master/MasterServiceSpec.scala, src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2Spec.scala, src/test/scala/io/hydrosphere/mist/master/logging/LogWriterSpec.scala
=> add job arguments validation at master.

src/main/scala/io/hydrosphere/mist/Messages.scala, src/main/scala/io/hydrosphere/mist/master/WorkerLink.scala, src/main/scala/io/hydrosphere/mist/master/WorkersManager.scala, src/main/scala/io/hydrosphere/mist/master/interfaces/jsonCodecs.scala, src/main/scala/io/hydrosphere/mist/worker/ClusterWorker.scala, src/main/scala/io/hydrosphere/mist/worker/SparkUtils.scala, src/main/scala/io/hydrosphere/mist/worker/WorkerActor.scala, src/test/scala/io/hydrosphere/mist/master/WorkerManagerSpec.scala, src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiSpec.scala, src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2Spec.scala, src/test/scala/io/hydrosphere/mist/worker/SparkUtilsSpec.scala, src/test/scala/io/hydrosphere/mist/worker/WorkerActorSpec.scala
Provide spark ui address with worker info
=> Close #265

.travis.yml, Jenkinsfile
- cache ui_local on travis
- jenkins - fix problems at last stage
=> Fixes for jenkins/travis

src/main/scala/io/hydrosphere/mist/master/MasterService.scala
for jobs with streaming support set run mode to exclusive ignoring context configuration
=> select run mode based on job`s class

src/main/scala/io/hydrosphere/mist/master/configs.scala, src/main/scala/io/hydrosphere/mist/worker/Worker.scala
- Fix worker arguments parsing
- Fix master configuration resolution
=> Hotfix - master worker hosts configuration

docs/http_api.md, mist.sbt, project/plugins.sbt, src/main/scala/io/hydrosphere/mist/master/interfaces/http/HttpV2Routes.scala, src/main/scala/io/hydrosphere/mist/master/interfaces/http/models.scala, src/main/scala/io/hydrosphere/mist/master/interfaces/jsonCodecs.scala, src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2Spec.scala
available at `/v2/api/status`
Close #270
=> Status route for http

Jenkinsfile
Test report example -
https://jenkins.hydrosphere.io/job/hydrosphere/job/mist/job/feature%252Fjenkins-test-results/lastCompletedBuild/testReport/
or https://jenkins.hydrosphere.io/blue/organizations/jenkins/hydrosphere%2Fhydro-serving/detail/master/35/tests
=> Added tests result collector

mist-lib/src/main/scala/mist/api/args/ArgCombiner.scala, mist-lib/src/main/scala/mist/api/args/Normalizer.scala, mist-lib/src/main/scala/mist/api/args/ToHandle.scala, mist-lib/src/main/scala/mist/api/args/WithArgsScala.scala, mist-lib/src/main/scala/mist/api/args/extractors.scala, mist-lib/src/test/scala/mist/api/TestSparkContext.scala, mist-lib/src/test/scala/mist/api/args/ArgDefSpec.scala, mist-lib/src/test/scala/mist/api/args/WithArgsScalaSpec.scala, mist.sbt, project/misc.scala, project/plugins.sbt
Now mists uses manually shaded [artifact](https://oss.sonatype.org/content/repositories/staging/io/hydrosphere/shadedshapeless_2.11/2.3.0/)
=> Shade shapeless

mist-lib/src/main/scala/mist/api/args/extractors.scala, mist-lib/src/test/scala/mist/api/args/UserArgsSpec.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/interfaces/jsonCodecs.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/interfaces/AnyJsonTest.scala
Fix double and long args.
Drop byte/short/float extractors.
=> fix argument extraction 

bin/mist-job-info-provider, configs/logging/log4j.debug.properties, configs/logging/log4j.default.properties, configs/logging/log4j.infoprovider.properties, docker-entrypoint.sh, mist-lib/src/main/scala/mist/api/internal/BaseJob.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/interfaces/http/HttpV2Routes.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2Spec.scala, mist/worker/src/main/resources/job-extractor.conf, mist/worker/src/main/scala/io/hydrosphere/mist/job/JobInfoExtractor.scala, mist/worker/src/main/scala/io/hydrosphere/mist/job/JobInfoProviderActor.scala
- Fix artifact downloading for docker mode
- InfoProvider
- use `lastModified` instead of calculating sha of artifact
- fix logging
- fix #391
=> Several fixes

mist/master/src/main/resources/master.conf, mist/master/src/main/scala/io/hydrosphere/mist/master/MainService.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/Messages.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/ContextEvent.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/ContextFrontend.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/ExecutionService.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/JobActor.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/status/JobStatusFlusher.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/status/ReportedEvent.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/status/StatusReporter.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/status/StoreFlusher.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/ContextFrontendSpec.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/ExecutionServiceSpec.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/JobActorSpec.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/status/JobStatusFlusherSpec.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/status/StatusReporterSpec.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/status/StoreFlusherSpec.scala
Fix connection leak on context frontend
=> Fix job cancellation - respond with correct job details

mist/worker/src/main/scala/io/hydrosphere/mist/worker/WorkerActor.scala
Remove unimportant information from error message
=> job execution - fix error message building

mist/master/src/main/scala/io/hydrosphere/mist/master/execution/ContextFrontend.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/execution/ContextFrontendSpec.scala
Fix possible situation with assigning workers to perform cancelled jobs
=> job cancellation

.gitignore, mist-lib/src/main/python/setup.py, mist/master/src/main/scala/io/hydrosphere/mist/master/JobDetailsRequest.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/execution/JobActor.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/interfaces/http/HttpV2Routes.scala, mist/master/src/main/scala/io/hydrosphere/mist/master/store/JobRequestSql.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/interfaces/http/HttpApiV2Spec.scala, mist/master/src/test/scala/io/hydrosphere/mist/master/store/JobRequestsSqlSpec.scala, mist/worker/src/main/scala/io/hydrosphere/mist/worker/WorkerActor.scala, project/Ui.scala
- JobActor: job may be failed in `file-downloading` state
- Http API: return error stack traces
- Fix SQL building for job history
- MistLib: Fix python test running
=> Error handing fixes
